### ISSUE TITLE
noPlayerFriendlyFire: true Not Working

### ISSUE THREAD

**Issue by Resoluciones** [Scyntrus/FactionMobs#13]
Hi!

Would it be possible to fix the noPlayerFriendlyFire: true notworking?

Thanks!

**Comment by Scyntrus** [comment]
Version numbers please.

**Comment by Scyntrus** [comment]
And explain the situation you experienced where it didn't work. I just tried having an archer shoot a zombie behind me and the arrows bounced off as expected.

**Comment by Resoluciones** [comment]
Hi, I'm glad you are "alive"!!

- FactionMobs version: 3.2.5_1.12-R0.1
- Feudal version: 1.9.0
- FactionsMobs config: https://hasteb.in/rixevujozi.sm
- Server IP: 176.31.117.222:25574
- It happens with lastest compilations of Spigot and Paper.
- I don't have any combat plugin.

Let me know!

Thanks!

**Comment by Resoluciones** [comment]
I will try to find out what plugin is conflicting then!

**Comment by Resoluciones** [comment]
There was not plugin conflicting.  The problem was inside messages.yml, but I didn't understand clearly what hapenned, I just regererated that plugin.   Anyway, what is important is that is working again!

Thanks.
