### ISSUE TITLE
Compiling with Less Dependencies

### ISSUE THREAD

**Issue by Resoluciones** [Scyntrus/FactionMobs#14]
Hi Scyntrus,

I've read your readme: "If you are compiling for yourself, you can delete the unused packages under "com.gmail.scyntrus.ifactions"  The corresponding team plugin dependencies can be removed from the pom.xml  By default, the pom file is configured to look for these jars in the lib folder  "

And I was trying to follow those guidlines, and compile it with only Feudal support, but I couldn't get a workable .jar, I think something more has to be done, not just removing the dependencies from pom and deleting the packages.

Can you let me know?

Thanks!

**Comment by Scyntrus** [comment]
Did you build with Maven?

**Comment by Resoluciones** [comment]
Yes, with Maven normal command: /mvn clean package

**Comment by Scyntrus** [comment]
How much of it is working? What is in the jar that gets output? If you are building for Feudal you also need the Turrets jar, otherwise you can delete the TurretsListener class and any reference to it.

**Comment by Resoluciones** [comment]
[FactionMobs.zip](https://github.com/Scyntrus/FactionMobs/files/1694737/FactionMobs.zip)

Yes I did that already, I get the attached .jar and after starting I get this error: https://hasteb.in/elomebuceq.avrasm

I've bought Feudal, just in case you ask (not a nulled copy).

**Comment by Scyntrus** [comment]
Well don't delete the com.gmail.scyntrus.ifactions.feudal package

**Comment by Resoluciones** [comment]
If you mean these files, they were not deleted.
![package](https://user-images.githubusercontent.com/29935874/35839532-a6bc0fd8-0acf-11e8-9ed8-e09eef81f59a.jpg)

**Comment by Scyntrus** [comment]
Don't delete the entire FeudalConnector, only delete the 4 lines that use the TurretsListener.

**Comment by Resoluciones** [comment]
It's solved!  Thank you Scyntrus!
