### ISSUE TITLE
Cooldown Between Spawns

### ISSUE THREAD

**Issue by Resoluciones** [Scyntrus/FactionMobs#15]
Hi Scyntrus!

Do you think it would be possible to add a configurable cooldown between each mob spawn?

Thanks!

**Comment by Scyntrus** [comment]
There are other plugins that can add cooldowns to commands.

**Comment by Resoluciones** [comment]
Yes, I have set it already.  But those plugins set cooldowns for each player not for the event in general.  So different people from different factions can spawn mobs at the same time, anyway.

**Comment by Scyntrus** [comment]
Cleaning up old issues. For limiting spawning, my suggestion is use an economy based limitation, such as being awarded money at set intervals, instead of me having to add more options.
