### ISSUE TITLE
FactionMobs inside Worldguard Regions

### ISSUE THREAD

**Issue by Resoluciones** [Scyntrus/FactionMobs#16]
Would it be possible to avoid FactionMobs entering Worldguard regions?  Or maybe despawning them if they enter.  Also, in case that's not possible, can it be possible to set to nodamage when they are in those regions?

I have this [plugin](https://dev.bukkit.org/projects/wg-eliminate), to avoid having mobs inside those regions, but it is not working with FM, unfortunately.

Thanks!

**Comment by Scyntrus** [comment]
Checking for this would add a lot of overhead. I don't want to implement it.
