### ISSUE TITLE
Mobs/Guards Turns Invisible After Server Restart/Reload

### ISSUE THREAD

**Issue by tungbox** [Scyntrus/FactionMobs#17]
After I turned off my server or reload it, the guards are all invisible? Creepy..

**Comment by TungBox** [comment]
Im not using LibDisguises but Im using a free minecraft hosting service called Serveromat, the bugs seems to disappear if I reload my server for a several times. But they deleted my server (with tons of works I have done to it) a while ago because I forgot to renew it, Quite sad thought.
