### ISSUE TITLE
FactionMobs won't charge money or power to spawn

### ISSUE THREAD

**Issue by slashbang45** [Scyntrus/FactionMobs#19]
I'm running a server on 1.11.2 with Factions and FactionMobs (v3.2.1). Everything looks to be set correctly in the config file, however nothing is being charged whether its money or power to spawn mobs. I have tried both and also having both charge types enabled at the same time and none seem to work.

I am also using EssentialX and Vault

**Comment by Scyntrus** [comment]
Did you make sure you don't have the fmob.bypass permission?
