### ISSUE TITLE
Error log spam

### ISSUE THREAD

**Issue by InfroDaz** [Scyntrus/FactionMobs#21]
Here is a error log generated after a day of the work of the plugin:
https://cdn.discordapp.com/attachments/358630608747888651/469420193907474442/error.log

Here is a plugin config:
https://cdn.discordapp.com/attachments/358630608747888651/469420368394846218/config.yml

Also messages, if needed:
https://cdn.discordapp.com/attachments/358630608747888651/469420365349781504/messages.yml

**Comment by Scyntrus** [comment]
Fixed
https://github.com/Scyntrus/FactionMobs/commit/f48f851cd2b36d43ac1f57c074032729a5a68dae
