### ISSUE TITLE
Players can't build in a chunk

### ISSUE THREAD

**Issue by HiddenCloud** [Scyntrus/FactionMobs#7]
Hi, one of my players has a very strange problem with not being able to place blocks in a chunk. I've checked out everything, and it turns out that it only happens if there's a factionmob in the chunk of the player. You can destroy blocks, but not place them, even with ops I've only managed to 'place' by using worldedit.  This bug happens very rarely and most of the time it resolves itself after a while by maybe killing the faction mobs, not a single error is thrown when this happens. I've had this before during 1.7 then it didn't show up for a while and now it happens again. I know it's very vague but I'm sure FactionMobs is the cause of this issue.

**Comment by Scyntrus** [comment]
I recently suppressed all exceptions from displaying in the console, but they're all logged in the FactionMobs/error.log file. Check to see if there's anything in there.

**Comment by HiddenCloud** [comment]
No, it's empty.

**Comment by Scyntrus** [comment]
I can't think off the top of my head of anything that would make this happen. Do you have a way of reliably reproducing the bug?

**Comment by Scyntrus** [comment]
Also, the error.log file is cleared every time the server starts, so you have to check the log before you restart your server.

**Comment by Scyntrus** [comment]
Closed for inactivity
