### ISSUE TITLE
Faction mobs nearly crashing server

### ISSUE THREAD

**Issue by ReaperAngels** [Scyntrus/FactionMobs#8]
I had a demonstration of faction mobs, and the fact that it is related to faction power. So the player spawned one, archer, and he couldn't spawn anymore as he needed more power. But, it became night and a spider wandered over. Then the server just slowed. I looked at the error log, but I had to shutdown the server, so it cleared. I do have the server log though. 
[20:15:34] [Server thread/ERROR]: Could not pass event EntityTargetLivingEntityEvent to FactionMobs v2.9.4_1.9-R0.1. I'll attach the log. Any thoughts on the reason?

And sorry about the zip file, but uncompressed it's 63MB.
[2016-04-30-6.zip](https://github.com/Scyntrus/FactionMobs/files/245109/2016-04-30-6.zip)

**Comment by Scyntrus** [comment]
It seems an update to CraftBukkit 12 days ago caused an infinite recursion bug. I'll start working on this.

**Comment by Scyntrus** [comment]
Fixed by
fa1066a7a8a2dd223de2eefe0e3ca62893d05a66
