### ISSUE TITLE
Change Aggro settings Faction

### ISSUE THREAD

**Issue by Mihawka** [Scyntrus/FactionMobs#9]
Hello
Is it possible to make the neutral faction is attacked by mobs faction?
For exemple : A Faction "A" which is neutral relationship with Faction "B".
The titan of the Faction "A" attack the faction "B" without a faction put the "B" enemy.

Is it possible ?

**Comment by Scyntrus** [comment]
It is possible, but I will not implement it in the plugin, since the current users of the plugin expect it to function as it already does. If you want, you can fork the plugin and make the modification yourself, for use on your own server.

**Comment by Mihawka** [comment]
Just change in the package Faction and class Faction Neutral Faction -1 ?

**Comment by Scyntrus** [comment]
If you're using Factions 2, you would set this value to -1 from 0.
https://github.com/Scyntrus/FactionMobs/blob/master/src/com/gmail/scyntrus/ifactions/f2/Faction2.java#L28

**Comment by Mihawka** [comment]
I am unable to import your project on my Eclipse :(
Can you help me or do the plugin for me please ?

**Comment by Mihawka** [comment]
I am in 1.7.10 with Favtion plugin 2.7.3

**Comment by Scyntrus** [comment]
1.7 is really old and unsupported. There's been many bugfixes since then so it's not a good idea to go back to such an old version.

**Comment by Scyntrus** [comment]
To give you an idea, this is the last 1.7 version.
8b5f13123562b4a30ec05c806b61c0c4933dbd99

**Comment by Scyntrus** [comment]
Closed for inactivity
